[package]
name = "grpc-calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.11"
tokio = { version = "1", features = ["full"]   }
prost = "0.12"

[build-dependencies]
tonic-build = "0.11"