build:
	cargo build
run:
	cargo run

check:
# Why would you not want an executable? 
# Often, cargo check is much faster than cargo build, 
#   because it skips the step of producing an executable
	cargo check

release:
# to compile it with optimizations
	cargo build --release